controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_video:
    path: '/entity/watch/{id}'
    controller: 'App\Controller\VideoController::watchVideo'
